CREATE TABLE CURRENCY   
(IN_CURRENCY INTEGER, 
CODE VARCHAR(50) CONSTRAINT CODEREQ NOT NULL, 
NAMED VARCHAR(100) CONSTRAINT NAMEDREQ NOT NULL,

CONSTRAINT PKIN_CURRENCY PRIMARY KEY (IN_CURRENCY),
CONSTRAINT UNIQUENAMED UNIQUE (NAMED) 
);

CREATE TABLE BANKS
(IN_BANKS INTEGER,
NAMED VARCHAR(100) CONSTRAINT NREQ NOT NULL, 

CONSTRAINT PKIN_BANKS PRIMARY KEY (IN_BANKS),
CONSTRAINT UNIQUEN UNIQUE (NAMED) 
);

CREATE TABLE COMPANIES
(IN_COMPANIES INTEGER,
NAMED VARCHAR(200) CONSTRAINT NREQ NOT NULL,
HEAD VARCHAR(500), 
ACCOUNTANT VARCHAR(500),  

CONSTRAINT PKIN_COMPANIES PRIMARY KEY (IN_COMPANIES),
CONSTRAINT UNIQUENC UNIQUE (NAMED) 
);

CREATE TABLE LOANS
(
IN_LOAN INTEGER,
IN_COMPANIES INTEGER,
IN_BANKS INTEGER,
IN_CURRENCY INTEGER, 
AMOUNT DECIMAL (20,2),
INTEREST DECIMAL (5,2),
STARTD DATE,
ENDD DATE,  
KIND VARCHAR (100),

CONSTRAINT PKIN_LOAN PRIMARY KEY (IN_LOAN),
CONSTRAINT FKIN_COMPANIES FOREIGN KEY (IN_COMPANIES) REFERENCES COMPANIES (IN_COMPANIES),
CONSTRAINT FKIN_BANKS FOREIGN KEY (IN_BANKS) REFERENCES BANKS (IN_BANKS),
CONSTRAINT FKIN_CURRENCY FOREIGN KEY (IN_CURRENCY) REFERENCES CURRENCY (IN_CURRENCY)
)