--DROP TABLE currency;
--DROP TABLE banks ;
--DROP TABLE companies ;
--DROP TABLE loans ;

CREATE TABLE CURRENCY   
(ID_CURRENCY INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
CODE VARCHAR(50) CONSTRAINT CODEREQ NOT NULL, 
NAMED VARCHAR(100) CONSTRAINT NAMEDREQ NOT NULL,

CONSTRAINT UNIQUENAMED UNIQUE (NAMED) 
);

CREATE TABLE BANKS
(ID_BANKS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
NAMED VARCHAR(100) CONSTRAINT NREQ NOT NULL, 

CONSTRAINT UNIQUEN UNIQUE (NAMED) 
);

CREATE TABLE COMPANIES
(ID_COMPANIES INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
NAMED VARCHAR(200) NOT NULL,
HEAD VARCHAR(500), 
ACCOUNTANT VARCHAR(500),  

CONSTRAINT UNIQUENC UNIQUE (NAMED) 
);

CREATE TABLE LOANS
(
ID_LOAN INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
ID_COMPANIES INTEGER,
ID_BANKS INTEGER,
ID_CURRENCY INTEGER, 
AMOUNT DECIMAL (20,2),
INTEREST DECIMAL (5,2),
START_DATE DATE,
END_DATE DATE,  
TYPE_LOAN VARCHAR (100),

CONSTRAINT FKIN_COMPANIES FOREIGN KEY (ID_COMPANIES) REFERENCES COMPANIES (ID_COMPANIES),
CONSTRAINT FKIN_BANKS FOREIGN KEY (ID_BANKS) REFERENCES BANKS (ID_BANKS),
CONSTRAINT FKIN_CURRENCY FOREIGN KEY (ID_CURRENCY) REFERENCES CURRENCY (ID_CURRENCY)
);